name: AWS Device Farm Automated Test for Mobile App

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::653827629504:role/DeviceFarm-GitHubActionRole
          aws-region: us-west-2

      - name: Schedule Device Farm Automated Test
        id: RunTest
        uses: aws-actions/aws-devicefarm-mobile-device-testing@v2.0
        with:
          run-settings-json: |
            {
              "name": "GitHubAction-${{ github.workflow }}_${{ github.run_id }}_${{ github.run_attempt }}",
              "projectArn": "arn:aws:devicefarm:us-west-2:653827629504:project:45a3ed36-19e7-442d-9bdd-17e4205ab634",
              "appArn": "arn:aws:devicefarm:us-west-2:653827629504:upload:45a3ed36-19e7-442d-9bdd-17e4205ab634/beeee8c0-ecc5-4403-a4e9-23576eda0d4e",
              "devicePoolArn": "arn:aws:devicefarm:us-west-2:653827629504:devicepool:45a3ed36-19e7-442d-9bdd-17e4205ab634/082d10e5-d7d7-48a5-ba5c-b33d66efa1f5",
              "test": {
                "type": "APPIUM_NODE",
                "testPackageArn": "arn:aws:devicefarm:us-west-2:653827629504:upload:45a3ed36-19e7-442d-9bdd-17e4205ab634/2fd35103-a952-4137-b2d4-3881d34ea745",
                "testSpecArn": "arn:aws:devicefarm:us-west-2:653827629504:upload:45a3ed36-19e7-442d-9bdd-17e4205ab634/604f5f80-78fa-4f12-b322-10d80d3ebc45",
              },
              "configuration": {
                "locale": "en_US",
                "location": { "latitude": 47.6204, "longitude": -122.3491 },
                "customerArtifactPaths": {
                  "deviceHostPaths": [ "$WORKING_DIRECTORY" ]
                },
                "radios": { "wifi": true, "bluetooth": false, "nfc": true, "gps": true },
                "billingMethod": "METERED"
              },
              "executionConfiguration": {
                "jobTimeoutMinutes": 150,
                "accountsCleanup": true,
                "appPackagesCleanup": true,
                "videoCapture": true,
                "skipAppResign": false
              }
            }
          artifact-types: ALL
          upload-poll-interval: 1000
          run-poll-interval: 30000

      - name: Upload results artifacts
        uses: actions/upload-artifact@v4
        with:
          name: AutomatedTestOutputFiles
          path: ${{ steps.RunTest.outputs.artifact-folder }}
